apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-controller
  namespace: traefik-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-controller
rules:
  - apiGroups: ['']
    resources: ['services', 'endpoints', 'secrets', 'configmaps']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['discovery.k8s.io']
    resources: ['endpointslices']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['gateway.networking.k8s.io']
    resources: ['gatewayclasses', 'gateways', 'httproutes', 'referencegrants']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-controller
subjects:
  - kind: ServiceAccount
    name: traefik-controller
    namespace: traefik-system
