providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All
deployment:
  kind: DaemonSet
hostNetwork: true
service:
  enabled: false
image:
  registry: registrii.local:5000
  repository: traefik
  tag: v2.10.7
updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
ingressRoute:
  dashboard:
    enabled: false
additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--log.level=debug"
ports:
  web:
    port: 80
    expose: false        # no Service needed; we’re on hostNet
  websecure:
    port: 443
    expose: false
    tls:
      enabled: true
