providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All
ports:
  web:
    port: :80
  websecure:
    port: :443
    tls:
      enabled: true
deployment:
  kind: DaemonSet
hostNetwork: true
service:
  enabled: false
image:
  registry: registrii.local:5000
  repository: traefik
  tag: v2.10.7
updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
ingressRoute:
  dashboard:
    enabled: false
additionalArguments:
  - "--log.level=debug"

