providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All
ports:
  web:
    port: 80
  websecure:
    port: 443
    tls:
      enabled: true
deployment:
  kind: DaemonSet
hostNetwork: true
service:
  enabled: false
image:
  registry: registrii.local:5000
  repository: traefik
  tag: v3.4.1
updateStrategy:
  rollingUpdate:
    maxUnavailable: 2
    maxSurge: 2
ingressRoute:
  dashboard:
    enabled: false
additionalArguments:
  - "--log.level=debug"
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

