---
# Offline setup of a Docker registry on the master node

- name: Ensure directory for Docker packages exists
  file:
    path: /tmp/docker_debs
    state: directory
    mode: '0755'
  become: yes

# Download the Docker engine .deb files from the master HTTP service
- name: Download Docker packages from asset server
  get_url:
    url: "http://{{ asset_server_host }}:{{ asset_server_port }}/pkgs/{{ item }}"
    dest: "/tmp/docker_debs/{{ item }}"
    mode: '0644'
    timeout: 30
  loop: "{{ registry_docker_packages }}"
  become: yes

# Install Docker from local packages
- name: Install Docker packages
  shell: dpkg -i /tmp/docker_debs/*.deb
  become: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

# Configure Docker daemon to use the insecure local registry
- name: Configure Docker daemon for insecure registry
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["{{ registry_host }}:{{ registry_port }}"],
        "allow-nondistributable-artifacts": ["{{ registry_host }}:{{ registry_port }}"]
      }
    mode: '0644'
  notify: Restart docker
  become: yes

- name: Set registry image tar name
  set_fact:
    registry_image_tar: "registry_{{ registry_version }}.tar"

# Load the registry image from local tarball
- name: Download registry image tarball from asset server
  get_url:
    url: "http://{{ asset_server_host }}:{{ asset_server_port }}/images/{{ registry_image_tar }}"
    dest: /tmp/registry.tar
    mode: '0644'
    timeout: 60
  become: yes

- name: Load registry image
  shell: docker load -i /tmp/registry.tar
  become: yes

- name: Ensure registry container is running
  shell: |
    if ! docker ps -a --format '{{"{{"}}.Names{{"}}"}}' | grep -q '^registry$'; then
      docker run -d -p {{ registry_port }}:5000 --restart=always --name registry registry:2
    else
      docker start registry
    fi
  args:
    executable: /bin/bash
  become: yes

# Define lists of images to load into the registry
- name: Define Kubernetes images
  set_fact:
    kube_core_images:
      - "kube-apiserver_v{{ kube_version }}.tar"
      - "kube-controller-manager_v{{ kube_version }}.tar"
      - "kube-scheduler_v{{ kube_version }}.tar"
      - "kube-proxy_v{{ kube_version }}.tar"
      - "etcd_3.5.16-0.tar"
      - "coredns_v1.11.3.tar"
      - "pause_3.10.tar"
    calico_images:
      - "cni_{{ calico_image_version }}.tar"
      - "node_{{ calico_image_version }}.tar"
      - "kube-controllers_{{ calico_image_version }}.tar"
    nvidia_plugin_image: "nvidia-device-plugin_{{ device_plugin_version }}.tar"
    traefik_image: "traefik_v{{ traefik_version }}.tar"
    python_image: "python_3.12-alpine.tar"
    whoami_image: "whoami_{{ whoami_version }}.tar"
    cunofs_images:
      - "csi-controller_latest.tar"
      - "csi-node_latest.tar"

# Download Kubernetes core image tarballs
- name: Download Kubernetes core images
  get_url:
    url: "http://{{ asset_server_host }}:{{ asset_server_port }}/images/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0644'
    timeout: 60
  loop: "{{ kube_core_images }}"
  become: yes

# Load Kubernetes core images and push them to the local registry
- name: Load and push Kubernetes core images
  shell: |
    img=$(docker load -i /tmp/{{ item }} | awk '/Loaded image:/ {print $3}')
    name=$(echo "$img" | awk -F/ '{print $NF}')
    docker tag $img {{ registry_host }}:{{ registry_port }}/$name
    docker push {{ registry_host }}:{{ registry_port }}/$name
  args:
    executable: /bin/bash
  loop: "{{ kube_core_images }}"
  become: yes

# Download Calico images
- name: Download Calico images
  get_url:
    url: "http://{{ asset_server_host }}:{{ asset_server_port }}/images/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0644'
    timeout: 60
  loop: "{{ calico_images }}"
  become: yes

# Load Calico networking images and push to the registry
- name: Load and push Calico images
  shell: |
    img=$(docker load -i /tmp/{{ item }} | awk '/Loaded image:/ {print $3}')
    name=$(echo "$img" | awk -F/ '{print $NF}')
    docker tag $img {{ registry_host }}:{{ registry_port }}/$name
    docker push {{ registry_host }}:{{ registry_port }}/$name
  args:
    executable: /bin/bash
  loop: "{{ calico_images }}"
  become: yes

# Download NVIDIA device plugin image
- name: Download NVIDIA device plugin image
  get_url:
    url: "http://{{ asset_server_host }}:{{ asset_server_port }}/images/{{ nvidia_plugin_image }}"
    dest: "/tmp/{{ nvidia_plugin_image }}"
    mode: '0644'
    timeout: 60
  become: yes

# Load NVIDIA device plugin image and push
- name: Load and push NVIDIA device plugin image
  shell: |
    img=$(docker load -i /tmp/{{ nvidia_plugin_image }} | awk '/Loaded image:/ {print $3}')
    # Preserve the repository path so the image is available as
    # <registry_host>:<registry_port>/nvidia/k8s-device-plugin:<tag>
    name=$(echo "$img" | cut -d/ -f2-)
    docker tag $img {{ registry_host }}:{{ registry_port }}/$name
    docker push {{ registry_host }}:{{ registry_port }}/$name
  args:
    executable: /bin/bash
  become: yes

# Traefik image for Gateway API controller
- name: Download Traefik image
  get_url:
    url: "http://{{ asset_server_host }}:{{ asset_server_port }}/images/{{ traefik_image }}"
    dest: "/tmp/{{ traefik_image }}"
    mode: '0644'
    timeout: 60
  become: yes

- name: Load and push Traefik image
  shell: |
    img=$(docker load -i /tmp/{{ traefik_image }} | awk '/Loaded image:/ {print $3}')
    name=$(echo "$img" | awk -F/ '{print $NF}')
    docker tag $img {{ registry_host }}:{{ registry_port }}/$name
    docker push {{ registry_host }}:{{ registry_port }}/$name
  args:
    executable: /bin/bash
  become: yes

# Python image for the sample application
- name: Download Python image for sample app
  get_url:
    url: "http://{{ asset_server_host }}:{{ asset_server_port }}/images/{{ python_image }}"
    dest: "/tmp/{{ python_image }}"
    mode: '0644'
    timeout: 60
  become: yes

- name: Load and push Python image
  shell: |
    img=$(docker load -i /tmp/{{ python_image }} | awk '/Loaded image:/ {print $3}')
    name=$(echo "$img" | awk -F/ '{print $NF}')
    docker tag $img {{ registry_host }}:{{ registry_port }}/$name
    docker push {{ registry_host }}:{{ registry_port }}/$name
  args:
    executable: /bin/bash
  become: yes

# whoami image for the traefik test service
- name: Download whoami image
  get_url:
    url: "http://{{ asset_server_host }}:{{ asset_server_port }}/images/{{ whoami_image }}"
    dest: "/tmp/{{ whoami_image }}"
    mode: '0644'
    timeout: 60
  become: yes

- name: Load and push whoami image
  shell: |
    img=$(docker load -i /tmp/{{ whoami_image }} | awk '/Loaded image:/ {print $3}')
    name=$(echo "$img" | awk -F/ '{print $NF}')
    docker tag $img {{ registry_host }}:{{ registry_port }}/$name
    docker push {{ registry_host }}:{{ registry_port }}/$name
  args:
    executable: /bin/bash
  become: yes

# cunoFS CSI driver images
- name: Download cunoFS images
  get_url:
    url: "http://{{ asset_server_host }}:{{ asset_server_port }}/images/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0644'
    timeout: 60
  loop: "{{ cunofs_images }}"
  become: yes

- name: Load and push cunoFS images
  shell: |
    img=$(docker load -i /tmp/{{ item }} | awk '/Loaded image:/ {print $3}')
    name=$(echo "$img" | awk -F/ '{print $(NF-1) "/" $NF}')
    docker tag $img {{ registry_host }}:{{ registry_port }}/$name
    docker push {{ registry_host }}:{{ registry_port }}/$name
  args:
    executable: /bin/bash
  loop: "{{ cunofs_images }}"
  become: yes

# Optional verification that the registry is serving
- name: Verify local registry catalog
  shell: curl -sf http://{{ registry_host }}:{{ registry_port }}/v2/_catalog
  register: registry_check
  changed_when: false
  become: yes
