---
# Deploy the cunofs CSI driver using offline manifests
- name: Set kubectl environment
  set_fact:
    kubectl_env:
      KUBECONFIG: /etc/kubernetes/admin.conf
  become: true

- name: Render cunofs license secret manifest
  template:
    src: license-secret.yaml.j2
    dest: /tmp/cunofs-license.yaml
    mode: '0644'
  become: true

- name: Apply cunofs license secret
  shell: kubectl apply -f /tmp/cunofs-license.yaml
  environment: "{{ kubectl_env }}"
  become: true

- name: Copy cunofs controller manifest
  copy:
    src: csi-controller.yaml
    dest: /tmp/cunofs-csi-controller.yaml
    mode: '0644'
  become: true

- name: Apply cunofs controller manifest
  shell: kubectl apply -f /tmp/cunofs-csi-controller.yaml
  environment: "{{ kubectl_env }}"
  become: true

- name: Copy cunofs node manifest
  copy:
    src: csi-node.yaml
    dest: /tmp/cunofs-csi-node.yaml
    mode: '0644'
  become: true

- name: Apply cunofs node manifest
  shell: kubectl apply -f /tmp/cunofs-csi-node.yaml
  environment: "{{ kubectl_env }}"
  become: true

- name: Copy storage class manifest
  copy:
    src: storageclass.yaml
    dest: /tmp/cunofs-storageclass.yaml
    mode: '0644'
  become: true

- name: Apply storage class manifest
  shell: kubectl apply -f /tmp/cunofs-storageclass.yaml
  environment: "{{ kubectl_env }}"
  become: true
