---
# Deploy the cunofs CSI driver using offline manifests
- name: Set kubectl environment
  set_fact:
    kubectl_env:
      KUBECONFIG: /etc/kubernetes/admin.conf
  become: true

- name: Ensure {{ cunofs_namespace }} namespace exists
  shell: |
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Namespace
    metadata:
      name: {{ cunofs_namespace }}
    EOF
  environment: "{{ kubectl_env }}"
  become: true


- name: Render cunofs license secret manifest
  template:
    src: license-secret.yaml.j2
    dest: /tmp/cunofs-license.yaml
    mode: '0644'
  become: true

- name: Apply cunofs license secret
  shell: kubectl apply -f /tmp/cunofs-license.yaml
  environment: "{{ kubectl_env }}"
  become: true

- name: Render cunofs controller manifest
  template:
    src: csi-controller.yaml.j2
    dest: /tmp/cunofs-csi-controller.yaml
    mode: '0644'
  become: true

- name: Apply cunofs controller manifest
  shell: kubectl apply -f /tmp/cunofs-csi-controller.yaml
  environment: "{{ kubectl_env }}"
  become: true

- name: Render cunofs node manifest
  template:
    src: csi-node.yaml.j2
    dest: /tmp/cunofs-csi-node.yaml
    mode: '0644'
  become: true

- name: Apply cunofs node manifest
  shell: kubectl apply -f /tmp/cunofs-csi-node.yaml
  environment: "{{ kubectl_env }}"
  become: true

- name: Copy storage class manifest
  copy:
    src: storageclass.yaml
    dest: /tmp/cunofs-storageclass.yaml
    mode: '0644'
  become: true

- name: Apply storage class manifest
  shell: kubectl apply -f /tmp/cunofs-storageclass.yaml
  environment: "{{ kubectl_env }}"
  become: true
